#-----------------------------------------------------------------
#
#           THIS FILE WAS AUTOGENERATED.
#
#           Visit https://github.com/jeancallisti/gdscript-strong-types
#
#
#-----------------------------------------------------------------


# This class is a utility class meant to represent an array of PCKPacker.
# it is not meant to be attached to a Node (unless you want to!)
# It exists in two versions (both named 'PCKPackerArray'): The one in CSharp style (CapitalLetters) or the one in GDScript style (snake_case).
# Just uncomment the version you like the most.

class_name PCKPackerArray

var a:Array = [];

func _crash(message: String):
    assert(false, message)

func _assert_PCKPacker(value: PCKPacker):
    if (!value is PCKPacker):
        _crash("value was expected to be of type PCKPacker")

func _assert_not_null_PCKPacker(value: PCKPacker):
    if (value == null):
        _crash("value was expected to be not null")
    _assert_PCKPacker(value)

func SetAt(position: int, value: PCKPacker):
    _assert_PCKPacker(value);
    a[position] = value;

func GetAt(position: int) -> PCKPacker:
    return a[position];

func Add(value: PCKPacker):
    _assert_PCKPacker(value);
    a.append(value);

# Same as Add, but with a different name.
func Append(value: PCKPacker):
    _assert_PCKPacker(value);
    a.append(value);

func Remove(position: int):
    a.remove(position);

func Size() -> int:
    return a.size();

func Clear():
    a.clear();

# func Contains(value: PCKPacker) -> bool:
#     _assert_PCKPacker(value);
#     return a.contains(value);

