#-----------------------------------------------------------------
#
#           THIS FILE WAS AUTOGENERATED.
#
#           Visit https://github.com/jeancallisti/gdscript-strong-types
#
#
#-----------------------------------------------------------------


# This class is a utility class meant to represent an array
# in which the values are of type 'PCKPacker'.
# It is not meant to be attached to a Node (unless you want to!)
# You can generate more classes like this one for your own types.
class_name PCKPackerArray

var a:Array = [];

func _crash(message: String):
    assert(false, message)

func _assert_PCKPacker(value: PCKPacker):
    if (!value is PCKPacker):
        _crash("value was expected to be of type PCKPacker")

func _assert_not_null_PCKPacker(value: PCKPacker):
    if (value == null):
        _crash("value was expected to be not null")

func set_at(position: int, value: PCKPacker):
    _assert_not_null_PCKPacker(value);
    _assert_PCKPacker(value);
    a[position] = value;

# Same as set_at but allows null
func set_at_nullable(position: int, value: PCKPacker):
    _assert_PCKPacker(value);
    a[position] = value;

func get_at(position: int) -> PCKPacker:
    return a[position];

func add(value: PCKPacker):
    _assert_not_null_PCKPacker(value);
    _assert_PCKPacker(value);
    a.append(value);

# Same as add but allows null
func add_nullable(value: PCKPacker):
    _assert_PCKPacker(value);
    a.append(value);

# Same as add, but with a different name.
func append(value: PCKPacker):
    _assert_not_null_PCKPacker(value);
    _assert_PCKPacker(value);
    a.append(value);

# Same as add_nullable, but with a different name.
func append_nullable(value: PCKPacker):
    _assert_PCKPacker(value);
    a.append(value);

func remove(position: int):
    a.remove(position);

func size() -> int:
    return a.size();

func clear():
    a.clear();

# func Contains(value: PCKPacker) -> bool:
#     _assert_PCKPacker(value);
#     return a.contains(value);

